export const videoData = [
  {
    id: 1,
    title: "Sample Video 1",
    imageUrl: "https://via.placeholder.com/2000",
    url: "/video",
  },
  {
    id: 2,
    title: "Sample Video 2",
    imageUrl: "https://via.placeholder.com/2000",
    url: "/video",
  },
  {
    id: 3,
    title: "Sample Video 3",
    imageUrl: "https://via.placeholder.com/2000",
    url: "/video",
  },
  {
    id: 4,
    title: "Sample Video 4",
    imageUrl: "https://via.placeholder.com/2000",
    url: "/video",
  },
  {
    id: 5,
    title: "Sample Video 5",
    imageUrl: "https://via.placeholder.com/2000",
    url: "/video",
  },
  {
    id: 6,
    title: "Sample Video 6",
    imageUrl: "https://via.placeholder.com/2000",
    url: "/video",
  },
  {
    id: 7,
    title: "Sample Video 7",
    imageUrl: "https://via.placeholder.com/2000",
    url: "/video",
  },
  {
    id: 8,
    title: "Sample Video 8",
    imageUrl: "https://via.placeholder.com/2000",
    url: "/video",
  },
  {
    id: 9,
    title: "Sample Video 9",
    imageUrl: "https://via.placeholder.com/2000",
    url: "/video",
  },
  {
    id: 10,
    title: "Sample Video 10",
    imageUrl: "https://via.placeholder.com/2000",
    url: "/video",
  },
  {
    id: 11,
    title: "Sample Video 11",
    imageUrl: "https://via.placeholder.com/2000",
    url: "/video",
  },
  {
    id: 12,
    title: "Sample Video 12",
    imageUrl: "https://via.placeholder.com/2000",
    url: "/video",
  },
  {
    id: 13,
    title: "Sample Video 13",
    imageUrl: "https://via.placeholder.com/2000",
    url: "/video",
  },
  {
    id: 14,
    title: "Sample Video 14",
    imageUrl: "https://via.placeholder.com/2000",
    url: "/video",
  },
  {
    id: 15,
    title: "Sample Video 15",
    imageUrl: "https://via.placeholder.com/2000",
    url: "/video",
  },
  {
    id: 16,
    title: "Sample Video 16",
    imageUrl: "https://via.placeholder.com/2000",
    url: "/video",
  },
  {
    id: 17,
    title: "Sample Video 17",
    imageUrl: "https://via.placeholder.com/2000",
    url: "/video",
  },
  {
    id: 18,
    title: "Sample Video 18",
    imageUrl: "https://via.placeholder.com/2000",
    url: "/video",
  },
  {
    id: 19,
    title: "Sample Video 19",
    imageUrl: "https://via.placeholder.com/2000",
    url: "/video",
  },
  {
    id: 20,
    title: "Sample Video 20",
    imageUrl: "https://via.placeholder.com/2000",
    url: "/video",
  },
];
